server:
  port: 9626

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          #username: dk.darshan1992@gmail.com
          #password: Darshan@1356
          uri: https://github.com/Darshua/cloudconfig
          clone-on-start: true
